/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import controlador.Escucha;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import modelo.TablaFunciones;
/** 
 *
 * @author Clint
 */
public class jdlVista extends javax.swing.JDialog {
 Escucha escucha ;


    
    
    /**
     * Creates new form LVista
     */
    
    DefaultTableModel modelo = new DefaultTableModel();
        TableRowSorter trs;
    public jdlVista(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }

    public jdlVista() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        btnTerminar = new javax.swing.JButton();
        txtPalabra2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtVentas = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTotal = new javax.swing.JTable();
        lbTotal = new javax.swing.JLabel();
        lbSeccion = new javax.swing.JLabel();
        lbInciso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel1.setText("Reconocimiento de voz ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 302, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Palabra");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 48, -1));

        btnIniciar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 160, 30));

        btnTerminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTerminar.setText("Terminar");
        getContentPane().add(btnTerminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 160, -1));

        txtPalabra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPalabra2ActionPerformed(evt);
            }
        });
        txtPalabra2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPalabra2KeyTyped(evt);
            }
        });
        getContentPane().add(txtPalabra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 230, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 730, -1, -1));

        jtVentas = new javax.swing.JTable(){
            public boolean isCellEditable(int fila,int col){
                return false;
            }
        };
        jtVentas.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jtVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sucursal", "Ciudad", "Estado", "Vendedor", "Producto"
            }
        ));
        jtVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtVentas.setFocusable(false);
        jtVentas.setRowMargin(4);
        jtVentas.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(jtVentas);
        if (jtVentas.getColumnModel().getColumnCount() > 0) {
            jtVentas.getColumnModel().getColumn(0).setHeaderValue("Sucursal");
            jtVentas.getColumnModel().getColumn(1).setHeaderValue("Ciudad");
            jtVentas.getColumnModel().getColumn(2).setHeaderValue("Estado");
            jtVentas.getColumnModel().getColumn(3).setHeaderValue("Vendedor");
        }

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 750, 260));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 460, 40, 20));

        jtTotal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " Total  MXN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtTotal.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jtTotal.setColumnSelectionAllowed(true);
        jtTotal.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtTotal);
        jtTotal.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 100, 70));

        lbTotal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTotal.setText("Total Ventas");
        getContentPane().add(lbTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 180, 30));

        lbSeccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 160, 30));

        lbInciso.setBackground(new java.awt.Color(153, 255, 255));
        lbInciso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbInciso, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 184, 370, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void txtPalabra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPalabra2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPalabra2ActionPerformed

    private void txtPalabra2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPalabra2KeyTyped
  
                        txtPalabra2.addKeyListener(new KeyAdapter() {
                    public void keyReleased (final KeyEvent e){
                    String cadena = (txtPalabra2.getText());
                    txtPalabra2.setText(cadena);
                    filtro ();
                   // Nombre();
                }
            });
            
            trs = new TableRowSorter(jtVentas.getModel());
           jtVentas.setRowSorter(trs);                 


// TODO add your handling code here:
    }//GEN-LAST:event_txtPalabra2KeyTyped
    
    
            public void filtro(){
  

    trs.setRowFilter(RowFilter.regexFilter(this.txtPalabra2.getText(), 0, 1, 2, 3, 4, 5 ));
}
 
   
      
    


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdlVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdlVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdlVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdlVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdlVista dialog = new jdlVista(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnIniciar;
    public javax.swing.JButton btnTerminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JTable jtTotal;
    public javax.swing.JTable jtVentas;
    public javax.swing.JLabel lbInciso;
    public javax.swing.JLabel lbSeccion;
    public javax.swing.JLabel lbTotal;
    public javax.swing.JTextField txtPalabra2;
    // End of variables declaration//GEN-END:variables


            

}
